import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from '@auth0/nextjs-auth0/client';
import Theme from "@/components/theme-provider";


export const metadata: Metadata = {
  title: "Maywood Sportsmen's Club",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
     <UserProvider>
      <body>
      <Theme
          >
        {children}
        </Theme>
      </body>
      </UserProvider>
    </html>
  );
}
